### ISSUE TITLE
chrome localdata show data formatter

### ISSUE THREAD

**Issue by FearrMe** [McBaumwolle/format_trakt_app_data#1]
https://gist.github.com/FearrMe/1a03351b310d1c027ae80dda821477e4

i've created a simple python script to format the chrome local data, very similar to the app data i reckon.
i'm very shit at both python and git so i'm not going to make a pull request as i don't want to put more effort into this
feel free to change anything and tell me if you need test data to use, @McBaumwolle

it looks like it can be easily modified for `watched_movies`(remove the loop for `ep_id`s and instead use `show` as the id, which will be the movie id).

output sample:

![image](https://i.imgur.com/b655Cs7.png)

more info(including how to retrieve local storage data) can be found by scrolling up on this twitter thread:
https://twitter.com/MongoliaGov/status/1604606801139314688
i had to browse an OS backup to be able to get the old local storage data back, so ymmv.

**Comment by McBaumwolle** [comment]
What a coincidence, I'm also very terrible at git! I use Firefox so I'll have to look at the cache or you can give me sample data, what works best for you.

**Comment by FearrMe** [comment]
https://gist.github.com/FearrMe/00176f015ff24b90cefd57ce2364df4e

i just entered some dummy data so the timestamps are gonna be very similar

used this addon to decompress (removed from chrome addon store for some reason): https://github.com/kriserickson/lz-localstorage-chrome-extension

**Comment by McBaumwolle** [comment]
Yes it works perfectly fine, thanks!
![grafik](https://user-images.githubusercontent.com/67203883/208417000-e28236df-4e1c-4310-be0f-dc562e54dfa8.png)

Should I just add this or how does GitHub work?
Edit: I invited you to the repo.

**Comment by FearrMe** [comment]
done

**Comment by McBaumwolle** [comment]
Perfect, thank you!
